version: '3.9'

services:
  carmovy_api:
    build: .
    container_name: carmovy_api
    image: carmovy-api:1.0.0
    depends_on:
      - carmovy_db
      - carmovy_cache
    command: >
      sh -c "
        composer install && composer dump-autoload
        php artisan key:generate
        php artisan serve
      "
    volumes:
      - ./:/var/www/api
    ports:
      - 81:8000
    networks:
      - carmovy-network
  
  carmovy_db:
    image: mysql:8.0.28
    container_name: carmovy_db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - carmovy-network

  carmovy_cache:
    image: redis:6.2
    container_name: carmovy_cache
    volumes:
      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: > 
      sh -c "
        redis-server /usr/local/etc/redis/redis.conf
      "
    ports:
      - 6379:6379
    networks:
      - carmovy-network
  
  carmovy_proxy:
    image: nginx:1.21.6
    container_name: carmovy_proxy
    depends_on:
      - carmovy_api
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/default.conf/:/etc/nginx/conf.d/default.conf
    networks:
      - carmovy-network
    
networks:
  carmovy-network:
    driver: bridge